name: Test Trailer Weight Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'  # Adjust to your Ruby version if different

      - name: Install dependencies
        run: |
          gem install rspec optparse

      - name: Run RSpec tests
        run: rspec --format documentation spec/
